version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/current/
permissions:
  - object: /var/www/current
    owner: rails
    group: rails
hooks:
  BeforeInstall:
    - location: script/deploy/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: script/deploy/after_install.sh
      timeout: 1800
      runas: root
  ApplicationStart:
    - location: script/deploy/application_start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: script/deploy/application_stop.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: script/deploy/validate_service.sh
      timeout: 300
      runas: root

