version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/current/
permissions:
  - object: /home/ec2-user/current
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: deploy/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: deploy/application_start.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: deploy/application_stop.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: deploy/validate_service.sh
      timeout: 300
      runas: ec2-user

